#Spectral & ShiftLeft Scan running on Azure DevOps pipeline2
trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
  - task: CmdLine@2
    displayName: Checkout $(Build.SourceBranchName)
    inputs:
      script: 'git checkout $(Build.SourceBranchName)'
  - script: |
      echo "Installing Spectral..."
      curl -L 'https://get.spectralops.io/latest/x/sh?dns=$(SPECTRAL_DSN)' | sh
      echo .
      echo "Scanning with Spectral"
      $HOME/.spectral/spectral scan --ok --dsn https://$(SPECTRAL_DSN) --include-tags base,audit
    displayName: "Spectral Scan"
      
  - script: |
      echo $(SPECTRAL_DSN)
      echo $(CHKP_CLOUDGUARD_ID)
      echo $(CHKP_CLOUDGUARD_SECRET)
    displayName: "Showing Variables"
  
  - script: |
      echo "Installing ShiftLeft..."
      curl -L 'https://shiftleft-prod-bucket.sg.iaas.checkpoint.com/blades/shiftleft/bin/linux/amd64/0.0.36/shiftleft' --output shiftleft
      chmod +x shiftleft
      cp shiftleft ~/bin
      export CHKP_CLOUDGUARD_ID=$(CHKP_CLOUDGUARD_ID)
      export CHKP_CLOUDGUARD_SECRET=$(CHKP_CLOUDGUARD_SECRET)
      export SHIFTLEFT_REGION=$(SHIFTLEFT_REGION) #Line used only if CG Native tenant is outside the US region (EU1 in Europe)
      echo "Scanning with ShiftLeft"
      ./shiftleft code-scan -r -2003 -e df014d15-df0b-456a-8d37-13df1f6f6950 -s ./
      echo . 
    displayName: "ShiftLeft Scan"
    
build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Container Image
        env: 
          CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
          CHKP_CLOUDGUARD_SECRET: ${{ secrets.CHKP_CLOUDGUARD_SECRET }}
        run: |
          git clone https://github.com/chkp-rolandop/demo-app
          docker build -t rolandopcp/myapp ./demo-app
          docker save -o myapp.tar rolandopcp/myapp
          chmod +x ./shiftleft
          ./shiftleft image-scan -i myapp.tar
  verify-infra:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check Terraform
        env:
          CHKP_CLOUDGUARD_ID: ${{ secrets.CHKP_CLOUDGUARD_ID }}
          CHKP_CLOUDGUARD_SECRET: ${{secrets.CHKP_CLOUDGUARD_SECRET }}
        run: |
          git clone https://github.com/chkp-rolandop/demo-app
          chmod +x ./shiftleft
          ./shiftleft iac-assessment -r -64 -p ./demo-app/terraform-template

  - script: |
      echo "Scan realizado com sucesso"
    displayName: "Scan finished"
